### PR TITLE
Add clearOnLoad parameter, small tweaks

### PR DESCRIPTION
**Pull request by chump29**
I added a clearOnLoad parameter for people like me who do not wish to retain the scratchpad logs between DCS sessions. I also cleaned up a few lines of code along the way.

### CODE REVIEW

**Comment by rkusa** [comment]
Thanks for the PR and cleanup! I am wondering whether it makes more sense to have this as an extension (based on #35). I'll give this some additional thought before I get back to the PR.

**Comment by rkusa** [comment]
@chump29 I understand the use-case of clearing the first page on load, but why would you want to clear all the pages on load? I'd be afraid that this is unexpected behaviour for most. At least I am using the first page for notes that don't really need to persist between sorties most of the time, but all my following pages are meant for persisting stuff like checklists and procedure notes.

**Comment by chump29** [comment]
@rkusa I only take notes per-mission for coordinates/notes, and do not need the persistence. If you do not think that this functionality will be widely used, please feel free to ignore it. I always side with more options = better. Maybe a `clearOnLoad` and `clearAllOnLoad`?

**Comment by rkusa** [comment]
#35 has an example plugin that adds a CLR button, that ones pressed, clears the current page (see also screenshot below):

Screenshot 2022-09-10 175359

What do you think about just having a button, or would you get a lot more value out of it when it happens automatically?

**Comment by chump29** [comment]
If there was a button to click to clear the current page, that would work. I would probably not use the other keypad buttons. It makes sense that you would want persisted notes for checklists, etc.

**Comment by rkusa** [comment]
The other buttons are also another extension, so you will be able to have the single "CLR" button and that is it. I'd go for not adding the automatic clearing of the Scratchpad then, and see if the "CLR" button works for everyone wanting something like this (as your request is not the first one in that direction). Thanks again anyway for the effort you put into this! Feel free to extract the cleanup changes into a separate PR.

**Pull request closed without merging**
